config/routes.rb
Rails.application.routes.draw do


  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}

    
    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end 
      end
    end

    resources :billings, only: [] do
      collection do
        get 'pre_pay'
        get 'execute'
      end
    end
   	
    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs' 
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/share/_footerC.html.erb
<div class="container-fluid bottom" style="background-color: #2b2b2b"> 
	<div class="row">
		<div class="offset-md-1 col-md-7" style="color: #fff">
			<h5>COPYRIGHT 2018 - FELIPE MAHANA</h5>
		</div>
	</div>	
</div>

app/views/share/_footerL.html.erb
<div class="container-fluid bottom" style="background-color: #42b649">
	<div class="row">
		<div class="offset-md-1 col-md-2">
			<h5>Mas informacion</h5>
			<%= link_to "Contactos", contact_path %>
			<br>
			<%= link_to "Terminos y Condiciones",terms_and_conditions_path %>
		</div>
		<div class="offset-md-1 col-md-3">
			<h5>Redes Sociales</h5>
			<a target="_blank" href="https://www.instagram.com">Instagram</a>			
			<a target="_blank" href="https://www.facebook.com/">Facebook</a>
			<a target="_blank" href="https://twitter.com">Twitter</a>
		</div>
	</div>	
</div>

app/views/share/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #42b649">
    <a class="navbar-brand" href="<%= root_path %> ">Logo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <%# if current_user.admin? or current_user.professional?%>
          <% if can?(:create, :program) %>
            <li class="nav-item">
              <%= link_to "Contratos", user_contracts_path, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to "Programas(x)", user_programs_path, class: 'nav-link'%>
            </li>
          <% end %>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? and current_user.role == 'guest'%>
          <li class="nav-item">
            <% if current_user.name.present? %>
              <%= link_to current_user.name, profile_path, class: 'nav-link' %>
            <% else %>
              <%= link_to current_user.email, profile_path, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% elsif user_signed_in? and current_user.role != 'guest'%>
          <li class="nav-item">
            <% if current_user.name.present? %>
              <%= link_to current_user.name, user_contracts_path, class: 'nav-link' %>
            <% else %>
              <%= link_to current_user.email, user_contracts_pathh, class: 'nav-link' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
</nav>