config/routes.rb
Rails.application.routes.draw do


  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}

    
    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end 
      end
    end

    resources :billings, only: [] do
      collection do
        get 'pre_pay'
        get 'execute'
      end
    end
   	
    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs' 
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :contract
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new, :user_programs]
    before_action :set_program, only: [:edit, :show, :update]
    before_action :set_user, only: [:new, :edit, :show, :update]
    before_action :set_contract, only: [:new,:create, :edit, :show, :update]
    before_action :set_plan, only: [:new, :edit, :show, :update]
    before_action :program_params, only: [:create, :update]
    authorize_resource
    
    def user_programs
        @programs = Program.all
    end

    def new
        @program = Program.new
    end

    def edit
      
    end


    def show

    end

    def update  
        @program.contract_id = params[:contract_id]
        @program.update(program_params)    
        if @program.update(program_params)
            redirect_to user_programs_path, notice: 'El programa se a actualizado con exito'
        else
            redirect_to user_programs_path, notice: 'El programa no se a actualizado'
        end
    end

    def create
        @program = Program.new(program_params)
        @program.contract = @contract
        @contract.pending = false

        if @program.save and @contract.save
             redirect_to user_contracts_path, notice: 'Se creo programa con exito'
        else
            redirect_to user_contracts_path, notice: 'No se pudo crear programa'
        end
    end

    private


    def program_params	 
		params.require(:program).permit(:training, :nutrition, :plan_id, :contract_id, :user_id)
	end

    def set_program
        @program = Program.find(params[:id])
    end 

    def set_user
        @user = User.find(params[:user_id])
    end

    def set_contract
        @contract = Contract.find(params[:contract_id])
    end

    def set_plan
        @plan = Plan.find(params[:plan_id])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/edit.html.erb
<% if @plan.contract_type == 1%>
	<h3>Realización de Plan Entrenamiento</h3>
<% elsif @plan.contract_type == 2 %>
	<h3>Realización de Plan Nutricional </h3>
<% else %>
	<h3>Realización de Plan Entrenamiento y nutricion</h3> 
<% end %>


<div class="row">
	<div class="col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<% if @user.name.present? %>
					<h5 class="card-title"> <%= @user.name %> </h5>
				<% else %>
					<h5 class="card-title"> <%= @user.email %> </h5>
				<% end %>
				<p class="card-title">Objetivo: <%= @contract.goal %> </p>
				<p class="card-text">Tipo plan: </p>
				<p class="card-text">Duracion plan: </p>
				<p class="card-text">Descripcion o tipo(?): <%= @plan.description %> </p>
		 	</div>
		</div>		  
	</div>
	<div class="offset-md-2 col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<h5 class="card-title"> Datos Cliente </h5>
				<p class="card-title">Edad: <%= @contract.age %> </p>
				<% if @contract.sex == 1 %>
					<p class="card-title">Sexo: Masculino </p>
				<% else %>
					<p class="card-title">Sexo: Femenino </p>
				<% end %>
				<p class="card-text">Peso: <%= @contract.weight %> kg </p>
				<p class="card-text">Estatura: <%= @contract.height %> cms </p>
				<p class="card-text">BMR: <%= @contract.bmr %> Kcal</p>
				<p class="card-text">Actividad Fisica: <%= @contract.activity_level %> </p>
		 	</div>
		</div>		  
	</div>
</div>


<h4>Plan</h4>

<% if @plan.contract_type == 1 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :training %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'editar' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% elsif @plan.contract_type == 2 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :nutrition %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'editar' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% else %>

	<div class="row">	
		<div class="col-md-4 mb-4">
		<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
			<%=form.label :training %> <br>
			<%=form.text_area(:training, rows: 20, cols: 50) %>
			<br>
			<%=form.label :nutrition %> <br>
			<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
			<br>
			<%= form.submit 'editar' %>
			<br>
			<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/programs/index.html.erb
<h6>posiblemente no sea buena idea hacerlo en el index de programs (convención)</h6>
<% if @plan.contract_type == 1%>
	<h3>Realización de Plan Entrenamiento</h3>
<% elsif @plan.contract_type == 2 %>
	<h3>Realización de Plan Nutricional </h3>
<% else %>
	<h3>Realización de Plan Entrenamiento y nutricion</h3> 
<% end %>


<div class="row">
	<div class="col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<% if @user.name.present? %>
					<h5 class="card-title"> <%= @user.name %> </h5>
				<% else %>
					<h5 class="card-title"> <%= @user.email %> </h5>
				<% end %>
				<p class="card-title">Objetivo: <%= @contract.goal %> </p>
				<p class="card-text">Tipo plan: </p>
				<p class="card-text">Duracion plan: </p>
				<p class="card-text">Descripcion o tipo(?): <%= @plan.description %> </p>
		 	</div>
		</div>		  
	</div>
	<div class="offset-md-2 col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<h5 class="card-title"> Datos Cliente </h5>
				<p class="card-title">Edad: <%= @contract.age %> </p>
				<% if @contract.sex == 1 %>
					<p class="card-title">Sexo: Masculino </p>
				<% else %>
					<p class="card-title">Sexo: Femenino </p>
				<% end %>
				<p class="card-text">Peso: <%= @contract.weight %> kg </p>
				<p class="card-text">Estatura: <%= @contract.height %> cms </p>
				<p class="card-text">BMR: <%= @contract.bmr %> Kcal</p>
				<p class="card-text">Actividad Fisica: <%= @contract.activity_level %> </p>
		 	</div>
		</div>		  
	</div>
</div>


<h4>Plan</h4>

<% if @plan.contract_type == 1 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :training %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'crear' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% elsif @plan.contract_type == 2 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :nutrition %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'crear' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% else %>

	<div class="row">	
		<div class="col-md-4 mb-4">
		<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
			<%=form.label :training %> <br>
			<%=form.text_area(:training, rows: 20, cols: 50) %>
			<br>
			<%=form.label :nutrition %> <br>
			<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
			<br>
			<%= form.submit 'crear' %>
			<br>
			<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/programs/new.html.erb
<% if @plan.contract_type == 1%>
	<h3>Realización de Plan Entrenamiento</h3>
<% elsif @plan.contract_type == 2 %>
	<h3>Realización de Plan Nutricional </h3>
<% else %>
	<h3>Realización de Plan Entrenamiento y nutricion</h3> 
<% end %>


<div class="row">
	<div class="col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<% if @user.name.present? %>
					<h5 class="card-title"> <%= @user.name %> </h5>
				<% else %>
					<h5 class="card-title"> <%= @user.email %> </h5>
				<% end %>
				<p class="card-text">Tipo plan: </p>
				<p class="card-text">Duracion plan: </p>
				<p class="card-text">Descripcion o tipo(?): <%= @plan.description %> </p>
		 	</div>
		</div>		  
	</div>
	<div class="offset-md-2 col-md-4 mb-4">
		<div class="card">
			<div class="card-body text-center">
				<h5 class="card-title"> Datos Cliente </h5>
				<p class="card-title">Edad: <%= @contract.age %> </p>
				<% if @contract.sex == 1 %>
					<p class="card-title">Sexo: Masculino </p>
				<% else %>
					<p class="card-title">Sexo: Femenino </p>
				<% end %>
				<p class="card-text">Peso: <%= @contract.weight %> kg </p>
				<p class="card-text">Estatura: <%= @contract.height %> cms </p>
				<p class="card-text">BMR: <%= @contract.bmr %> Kcal</p>
				<p class="card-text">Actividad Fisica: <%= @contract.activity_level %> </p>
				<p class="card-title">Objetivo: <%= @contract.goal %> </p>
		 	</div>
		</div>		  
	</div>
</div>


<h4>Plan</h4>

<% if @plan.contract_type == 1 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :training %> <br>
				<%=form.text_area(:training, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'crear' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% elsif @plan.contract_type == 2 %>

	<div class="row">	
		<div class="col-md-4 mb-4">
			<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
				<%=form.label :nutrition %> <br>
				<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
				<br>
				<%= form.submit 'crear' %>
				<br>
				<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% else %>

	<div class="row">	
		<div class="col-md-4 mb-4">
		<%=form_with(model: [@plan, @contract, @user ,@program], local: true) do |form| %>
			<%=form.label :training %> <br>
			<%=form.text_area(:training, rows: 20, cols: 50) %>
			<br>
			<%=form.label :nutrition %> <br>
			<%=form.text_area(:nutrition, rows: 20, cols: 50) %>
			<br>
			<%= form.submit 'crear' %>
			<br>
			<%= link_to 'volver a user contracts', user_contracts_path %>
			<% end %>
		</div>
	</div>

<% end %>

app/views/programs/user_programs.html.erb
<h4>Tabla con usuarios y solicitud de edicion</h4>
<h5>Aun no terminado(no lista solo el ultimo)</h5> 
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Plan</th>
      <th>Duracion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.order("created_at").each do |program| %>
        <tr>
          <% if program.contract.user.name.present? %>
            <td><%= program.contract.user.name %></td>
          <% else %>  
            <td><%= program.contract.user.email %></td>
          <% end %>
          <td>
            <% if program.contract.plan.contract_type == 1 %>
              Plan Entrenamiento
            <% elsif program.contract.plan.contract_type == 2 %>
              Plan Nutricional
            <% else %>
              Plan Entrenamiento y Nutricional
            <% end %>
          </td>

          <td>
            <%= program.contract.plan.duration %>
          </td>


          <td>
             <!-- revisar parametros -->
            <%= program.contract.plan.id %>
            <%= program.contract.id %>
            <%= program.contract.user.id %>
            <%= program.id %>
            
            <%= link_to "Editar", edit_plan_contract_user_program_path(program.contract.plan.id,program.contract.id,program.contract.user.id,program.id) %>
            </td>
        </tr>      
    <% end %>
  </tbody>
</table>