config/routes.rb
Rails.application.routes.draw do


  #get 'programs/index'

  	devise_for :users, controllers: {
        sessions: 'users/sessions'

   	}

    
    resources :plans, only: [:index, :user_contracts] do
      resources  :contracts, only: [:index, :show, :create, :new, :edit, :update] do
        resources :user, only: [] do
          resources :programs, only: [:new,:create, :edit, :update, :show]
        end 
      end
    end

    resources :billings, only: [] do
      collection do
        get 'pre_pay'
        get 'execute'
      end
    end
   	
    get 'contact', to: 'plans#contact'
    get 'terms_and_conditions', to: 'plans#terms_and_conditions'
    get 'profile', to: 'plans#profile'
    get 'user_contracts', to: 'plans#user_contracts'
    get 'user_programs', to: 'programs#user_programs' 
    root 'plans#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
	has_many :contracts, dependent: :destroy
  	has_many :users, through: :contracts, dependent: :destroy
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!, only: [:user_contracts, :profile]
  def index
    @plans = Plan.all
  end

  def profile
    
  end

  def contact

  end

  def terms_and_conditions

  end

  def user_contracts
    @users = User.all
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/contact.html.erb
<h5>Datos Contacto</h5>

<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</div>
<div>Velit autem, quisquam dolorum facilis ullam praesentium doloribus error nobis facere.</div>
<div>Tempora aliquam amet labore blanditiis deserunt totam in eligendi perspiciatis modi consectetur fugiat deleniti officiis voluptatum repellat voluptates dolores expedita eveniet iure, delectus veritatis. Optio alias, nam esse. Alias, ex!</div>

app/views/plans/index.html.erb
<div class="container">
	<div class="row">
		<div class="offset-md-5 col-md-3">
			<h5>Quienes somos</h5>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>
	</div>
</div>


<div class="container">
	<div class="row">
		<div class="offset-md-5 col-md-3">
			<h5>Entrenamiento en línea</h5>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>
	</div>
</div>

<div class="row">
	<% @plans.order("duration").each do | plans | %>
		<div class="col-md-4 mb-4">
			<div class="card">
				<div class="card-body text-center">
					<% if plans.contract_type == 1%>
						<h5 class="card-title"> Plan Entrenamiento </h5>
					<% elsif plans.contract_type == 2 %>
						<h5 class="card-title"> Plan Nutricion </h5>
					<% else %>
						<h5 class="card-title"> Plan Entrenamiento con nutricion </h5>
					<% end %>
					<p class="card-title">Precio: $<%= plans.price %> </p>
					<p class="card-text">La duracion del plan <%= plans.duration %> mes o meses</p>
					<p class="card-text"><%= plans.description %> </p>
					<a href="<%= new_plan_contract_path(plans)%>" class="btn btn-success">Contratar</a>
			 	</div>
			</div>		  
		</div>
	<% end %>
</div>

<div class="container">
	<div class="row">
		<div class="offset-md-5 col-md-3">
			<h5>Preguntas Frecuentes</h5>
		</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
		</p>
	</div>
</div>

app/views/plans/profile.html.erb
<h3>Perfil</h3>
<% if current_user.name.present? %>
	<p>  Nombre: <%= current_user.name %> </p>
	<p>  Correo: <%= current_user.email %> </p>
<% else %>
	<p>  Correo: <%= current_user.email %> </p>
<% end %>
<h5>Datos</h5>
<p>Edad: <%= current_user.contracts.last.age %></p> 
<% if current_user.contracts.last.sex == 1 %>
	<p> Sexo: Masculino </p>
<% else %>
	<p>Sexo: Femenino </p>
<% end %>
<p>Peso: <%= current_user.contracts.last.weight %> kg</p> 
<p>Estatura: <%= current_user.contracts.last.height %> cms </p>

<h4>Entrenamiento</h4>
<% if current_user.contracts.last.try(:programs).present? %>
	<% if current_user.contracts.last.plan.contract_type==1 %>
		<h5>Rutina entrenamiento</h5>
		<p><%= current_user.contracts.last.programs.last.training %></p>
	<% elsif current_user.contracts.last.plan.contract_type==2 %>
		<h5>Plan Nutricional</h5>
		<p><%= current_user.contracts.last.programs.last.nutrition %></p>
	<% else %>
		<h5>Rutina entrenamiento</h5>
		<p><%= current_user.contracts.last.programs.last.training %></p>
		<h5>Plan Nutricional</h5>
		<p><%= current_user.contracts.last.programs.last.nutrition %></p>
	<% end %>
<% else %>
	<p>No tiene rutina de entrenamiento</p>
<% end %>

app/views/plans/terms_and_conditions.html.erb
<h5>Terminos y Condiciones</h5>

<div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa excepturi quo ipsum laborum illum repudiandae ut qui, autem odit magnam expedita aperiam reprehenderit distinctio ipsam, cum velit? Itaque animi, laborum.</div>
<div>Maxime inventore omnis voluptate error quos veniam aut, eius debitis eligendi quam unde quis excepturi quia minima architecto, nesciunt rerum. Nihil necessitatibus minus consectetur eligendi tenetur commodi, vitae, beatae odio?</div>
<div>Et obcaecati cupiditate harum, nam quos consequatur praesentium, non earum quasi quibusdam magnam laboriosam aperiam, amet est eveniet, blanditiis enim ex quia repudiandae accusamus dolore nobis repellat voluptates quis. Aliquid!</div>
<div>Repellendus modi fuga unde eveniet dolor distinctio voluptates, quia nobis necessitatibus dolore repellat, autem eligendi ullam quod deleniti. Culpa, praesentium quos tempore eum quia dignissimos sunt, eveniet exercitationem numquam! Maxime!</div>
<div>Aspernatur itaque doloremque facilis eveniet sint eligendi quaerat officiis, provident officia porro ipsum repudiandae rerum odio quasi. Voluptate vel minus aspernatur ab eveniet, odio vitae velit inventore, quia tempore totam!</div>

app/views/plans/user_contracts.html.erb
<h4>Tabla de usuarios con planes pendientes</h4> 
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Plan</th>
      <th>Fecha Contrato</th>
      <th>Duracion Plan(mes)</th>
      <th>Fecha Termino Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.order("created_at").each do |user| %>
      <% if user.contracts.present? and user.contracts.last.pending == true %>        
        <tr>
          <% if user.name.present? %>
            <td><%= user.name %></td>
          <% else %>
            <td><%= user.email %></td>
          <% end %>
          <td>
            <% unless user.contracts.last.nil? %>
              <% unless user.contracts.last.plan.nil? %>
                <% if user.contracts.last.plan.contract_type == 1%>
                  Plan Entrenamiento 
                <% elsif user.contracts.last.plan.contract_type == 2 %>
                  Plan Nutricional 
                <% else %>
                  Plan Entrenamiento y Nutricion 
                <% end %>
              <% end %>
            <% end %>   
          </td>

          <!-- ruby toma 1 mes como 2629746 segs (user.contracts.last.try(:created_at) + 2629746)-->

          <td>
              <% unless user.contracts.last.nil? %>
                <% start_date_conract=user.contracts.last.created_at %>
                <%#= user.contracts.last.created_at %>
                <%= user.contracts.last.created_at.strftime('%d/%m/%Y') %>
              <% end %>
          </td>

          <td>
            <% unless user.contracts.last.nil? %>
              <% unless user.contracts.last.plan.nil? %>
                <% duration_plans_mont=user.contracts.last.plan.duration.month %>
                <%= user.contracts.last.plan.duration %>
              <% end %>
            <% end %>
          </td>

          <td>
            <% end_date_contract=(start_date_conract+duration_plans_mont)%> 
            <%= end_date_contract.strftime('%d/%m/%Y')  %> 
          </td>

          <td>
             <!-- revisar parametros -->
            <%= user.contracts.last.plan.id %>
            <%= user.contracts.last.id %>
            <%= user.id %>
            
            <%= link_to "Realizar programa", new_plan_contract_user_program_path(user.contracts.last.plan.id,user.contracts.last.id,user.id) %>
            </td>
        </tr>
      <% end %>      
    <% end %>
  </tbody>
</table>